services:
  - type: web
    name: grandeur-api
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
